### PR TITLE
Add localization

### PR DESCRIPTION
**Pull request by humdingerb**
Plus:
* added vertical spacing below slider
* removed ":" from checkbox labels
* updated makefile to Haiku Generic Makefile v2.6
* cleanup of some stray spaces
* added English and German catkeys

### CODE REVIEW

**Comment by humdingerb** [comment]
Shall I upload the catkeys to [Polyglot](http://i18n.kacperkasper.pl/projects)?

**Comment by humdingerb** [comment]
Hi @noryb009, I just closed PR #2, a similar PR from 3 years ago I forgot about...
Are you still monitoring this thing, or would you maybe like to transfer the repo to HaikuArchives?

**Comment by noryb009** [comment]
Hi @humdingerb , thanks for the PR!

I'm sorry about missing your previous PR :( We can transfer the repo if you think it would make things easier for you in the future.

Please do upload the catkeys to Polyglot, thanks!

**Comment by humdingerb** [comment]
> We can transfer the repo if you think it would make things easier for you in the future.

Nah, as long as you're available once in a while to merge PRs to update localizations etc... :)
Catkeys uploaded to [Polyglot](https://i18n.kacperkasper.pl/projects/40).

**Pull request merged**
