### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by humdingerb**
Do you want to make an "official" 0.0.2 release of it? If so, don't forget to increase the version to 0.0.2 in OptiPNGTranslator.rdef.

### CODE REVIEW

**Comment by humdingerb** [comment]
@noryb009, got a second to merge the PR?
Plus maybe some more minutes to up the version and craft a release... Or not, you decide. :)

**Comment by humdingerb** [comment]
/me clears throat in @noryb009 's general direction... :)

**Comment by noryb009** [comment]
Hi @humdingerb , thanks for importing the translations! I wanted to do the release at the same time as merging, but this slipped down my email inbox. I will get to the release soon :)

**Comment by humdingerb** [comment]
Thanks!
 👍

**Pull request merged**
